version: '3.8'

services:
  web:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "8080:80"

  backend:
    build: .
    volumes:
      - .:/code
    links:
      - redis
    environment:
      - PORT_REDIS=6379
      - HOST_REDIS=redis
      - VIRTUAL_HOST=teste.docker
    labels:
      - 'app.environment=${ENV_APP}'

  redis:
    image: redis
    volumes:
      - dados_${ENV_APP}:/data
    labels:
      - 'app.environment=${ENV_APP}'

volumes:
  dados_devel: # Certifique-se de exportar ENV_APP=devel antes de rodar
