version: '3' # Versão do Docker Compose
services: 
  meu-blog: # Serviço do WordPress
    image: wordpress:6.2.2 # Imagem oficial do WordPress
    container_name: wordpress # Nome do container para fácil identificação
    restart: always # Reinicia automaticamente em caso de falha
    env_file:
      - .env # Carrega variáveis de ambiente do arquivo .env
    ports:
      - "8081:80" # Mapeia a porta 80 do container para a 8081 do host
    depends_on:
      - db # Garante que o banco de dados suba antes do WordPress
    volumes:
      - wordpress:/var/www/html # Volume para persistir dados do WordPress
    networks:
      - meu-blog # Conecta o serviço à rede personalizada
  db: # Serviço do banco de dados MySQL
    image: mysql:5.7 # Imagem oficial do MySQL
    container_name: mysql # Nome do container para fácil identificação
    restart: always # Reinicia automaticamente em caso de falha
    env_file:
      - .env # Carrega variáveis de ambiente do arquivo .env
    volumes:
      - db:/var/lib/mysql # Volume para persistir dados do banco
    ports:
      - "3306:3306" # Mapeia a porta 3306 do container para a 3306 do host
    networks:
      - meu-blog # Conecta o serviço à rede personalizada
networks:
  meu-blog:
    driver: bridge # Define o driver de rede como bridge (padrão para comunicação entre containers)
volumes:
  wordpress: # Volume nomeado para dados do WordPress
  db:        # Volume nomeado para dados do MySQL