version: '2'

services:
  web: 
    container_name: web
    build: web
    networks:
      - backend
    ports:
      - "8080:80"

  worker:
    build: worker
    networks:
      backend:
        aliases:
        - apps
    expose:
      - 80
    depends_on:
      - web

  redis:
    image: redis:3.2.8
    networks:
      - backend

networks:
  backend:
    driver: bridge