version: '2'

services:
  web: 
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    labels:
      - 'app.environment=${ENV_APP}'

  redis':
    image: redis
    volumes:
      - dados_devel:/data
    labels:
      - 'app.environment=${ENV_APP}'

volumes:
  dados_devel:
